# Generated by Django 5.2.17 on 2026-09-06 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CropListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Shankar-6 Cotton Lot 50 Qtl', max_length=200)),
                ('commodity', models.CharField(default='Cotton', max_length=100)),
                ('quantity_quintal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expected_price_per_quintal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location_district', models.CharField(max_length=100)),
                ('location_state', models.CharField(default='Gujarat', max_length=100)),
                ('quality_grade', models.CharField(default='Grade A', max_length=50)),
                ('harvest_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PENDING_DEAL', 'Pending Deal'), ('SOLD', 'Sold'), ('DELISTED', 'Delisted')], default='ACTIVE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop_lot', models.ForeignKey(blank=True, help_text="Optional link to farmer's registered crop lot", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketplace_listings', to='crops.croplot')),
                ('farmer', models.ForeignKey(limit_choices_to={'role': 'farmer'}, on_delete=django.db.models.deletion.CASCADE, related_name='crop_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Crop Listing',
                'verbose_name_plural': 'Crop Listings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BuyerInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offered_price_per_quintal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('requested_quantity_quintal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('message', models.TextField(blank=True, default='')),
                ('contact_phone', models.CharField(blank=True, default='', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('CLOSED', 'Closed')], default='PENDING', max_length=20)),
                ('farmer_notes', models.TextField(blank=True, default='', help_text="Farmer's response note")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(limit_choices_to={'role': 'buyer'}, on_delete=django.db.models.deletion.CASCADE, related_name='buyer_inquiries', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='marketplace.croplisting')),
            ],
            options={
                'verbose_name': 'Buyer Inquiry',
                'verbose_name_plural': 'Buyer Inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
