# Generated by Django 4.2.30 on 2026-09-04 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('markets', '0001_initial'),
        ('crops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation', models.CharField(choices=[('SELL_NOW', 'Sell Now'), ('HOLD', 'Hold'), ('PARTIAL_SELL', 'Partial Sell')], max_length=20)),
                ('current_net_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('expected_future_net_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('sell_quantity_suggestion', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('confidence', models.DecimalField(decimal_places=3, help_text='0.0 – 1.0', max_digits=4)),
                ('reasoning_factors', models.JSONField(default=dict)),
                ('rule_version', models.CharField(default='1.0.0', max_length=50)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('granite_explanation', models.TextField(blank=True, null=True)),
                ('best_market', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='markets.market')),
                ('crop_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='crops.croplot')),
            ],
            options={
                'verbose_name': 'Recommendation',
                'ordering': ['-generated_at'],
            },
        ),
    ]
