# Generated by Django 4.2.30 on 2026-09-04 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity', models.CharField(choices=[('cotton', 'Cotton'), ('groundnut', 'Groundnut')], max_length=20)),
                ('variety', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity in the specified unit', max_digits=10)),
                ('unit', models.CharField(choices=[('quintal', 'Quintal'), ('kg', 'Kilogram'), ('tonne', 'Tonne')], default='quintal', max_length=10)),
                ('moisture_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('quality_grade', models.CharField(blank=True, choices=[('A', 'Grade A (Premium)'), ('B', 'Grade B (Standard)'), ('C', 'Grade C (Below Standard)')], max_length=5, null=True)),
                ('harvest_date', models.DateField()),
                ('storage_status', models.CharField(choices=[('farm', 'At Farm'), ('warehouse', 'In Warehouse'), ('cold_storage', 'Cold Storage')], default='farm', max_length=20)),
                ('storage_start_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_lots', to='accounts.farmerprofile')),
            ],
            options={
                'verbose_name': 'Crop Lot',
                'verbose_name_plural': 'Crop Lots',
                'ordering': ['-created_at'],
            },
        ),
    ]
