# Generated by Django 5.2.17 on 2026-09-03 18:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=100)),
                ('taluka', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(default='Gujarat', max_length=50)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('market_type', models.CharField(choices=[('APMC', 'APMC (Government)'), ('private', 'Private Market')], default='APMC', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Market',
                'verbose_name_plural': 'Markets',
                'ordering': ['district', 'name'],
                'unique_together': {('name', 'district', 'state')},
            },
        ),
        migrations.CreateModel(
            name='MarketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity', models.CharField(choices=[('cotton', 'Cotton'), ('groundnut', 'Groundnut')], max_length=20)),
                ('variety', models.CharField(blank=True, max_length=100, null=True)),
                ('min_price', models.DecimalField(decimal_places=2, help_text='Minimum price (Rs/quintal)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_price', models.DecimalField(decimal_places=2, help_text='Maximum price (Rs/quintal)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('modal_price', models.DecimalField(decimal_places=2, help_text='Modal (most common) price (Rs/quintal)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('arrival_quantity', models.DecimalField(blank=True, decimal_places=2, help_text='Arrival quantity (quintals)', max_digits=12, null=True)),
                ('price_date', models.DateField(help_text='Date of the price record')),
                ('source', models.CharField(choices=[('agmarknet', 'Agmarknet'), ('manual', 'Manual Entry'), ('mock', 'Mock / Demo Data')], default='mock', max_length=20)),
                ('source_timestamp', models.DateTimeField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='markets.market')),
            ],
            options={
                'verbose_name': 'Market Price',
                'verbose_name_plural': 'Market Prices',
                'ordering': ['-price_date'],
                'indexes': [models.Index(fields=['commodity', 'market', 'price_date'], name='markets_mar_commodi_f3fa58_idx'), models.Index(fields=['price_date'], name='markets_mar_price_d_0d4861_idx')],
            },
        ),
    ]
