# Generated by Django 5.2.17 on 2026-09-06 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='marketprice',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='market',
            name='source',
            field=models.CharField(choices=[('apmc_directory', 'APMC Directory (Scraped)'), ('data_gov', 'data.gov.in'), ('manual', 'Manual')], default='apmc_directory', help_text='How this market record was populated.', max_length=30),
        ),
        migrations.AddField(
            model_name='market',
            name='source_url',
            field=models.URLField(blank=True, help_text='Source page URL if available.', null=True),
        ),
        migrations.AddField(
            model_name='marketprice',
            name='grade',
            field=models.CharField(blank=True, default='', help_text='Grade as reported by the source (e.g. FAQ, Bold).', max_length=100),
        ),
        migrations.AlterField(
            model_name='marketprice',
            name='source',
            field=models.CharField(choices=[('agmarknet', 'Agmarknet / data.gov.in'), ('manual', 'Manual'), ('mock', 'Mock/Demo')], default='mock', max_length=20),
        ),
        migrations.AlterField(
            model_name='marketprice',
            name='source_timestamp',
            field=models.DateTimeField(blank=True, help_text='When this record was retrieved from the source.', null=True),
        ),
        migrations.AlterField(
            model_name='marketprice',
            name='variety',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='marketprice',
            unique_together={('market', 'commodity', 'variety', 'price_date')},
        ),
    ]
