# Generated by Django 5.2.17 on 2026-09-03 18:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity', models.CharField(choices=[('cotton', 'Cotton'), ('groundnut', 'Groundnut')], max_length=20)),
                ('forecast_date', models.DateField(help_text='Date for which the price is predicted')),
                ('predicted_price', models.DecimalField(decimal_places=2, help_text='Predicted modal price (Rs/quintal)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('lower_bound', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('upper_bound', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('confidence_score', models.FloatField(blank=True, help_text='Confidence score 0–1', null=True)),
                ('model_name', models.CharField(default='linear_trend', max_length=100)),
                ('model_version', models.CharField(default='1.0', max_length=50)),
                ('horizon_days', models.IntegerField(default=14)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('is_mock', models.BooleanField(default=False)),
                ('market', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forecasts', to='markets.market')),
            ],
            options={
                'verbose_name': 'Forecast',
                'verbose_name_plural': 'Forecasts',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['commodity', 'market', 'forecast_date'], name='forecasting_commodi_bc28d2_idx')],
            },
        ),
    ]
